// ------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime : 16.0.0.0
//  
//     Les changements apportés à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SvdGenerator
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\Digital Consulting\source\repos\SvdGenerator\Memory.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class Memory : MemoryBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("#pragma once\r\n\r\n#include <array>\r\n#include <atomic>\r\n#include <cstddef>\r\n#include" +
                    " <cstdint>\r\n#include <tuple>\r\n#include <type_traits>\r\n\r\n/**\r\n * Represents both " +
                    "a clear and a set operand for a specific register.\r\n */\r\ntemplate<typename TReg>" +
                    "\r\nclass ClearSet\r\n{\r\npublic:\r\n\r\n\tconstexpr ClearSet(TReg clear, TReg set) : m_cl" +
                    "ear(clear), m_set(set) {}\r\n\r\n\tconstexpr auto operator||(ClearSet other) const ->" +
                    " ClearSet\r\n\t{\r\n\t\treturn ClearSet(m_clear | other.m_clear, m_set | other.m_set);\r" +
                    "\n\t}\r\n\r\n\tconstexpr auto clear() const -> TReg {return m_clear;}\r\n\tconstexpr auto " +
                    "set() const -> TReg {return m_set;}\r\n\r\nprivate:\r\n\tTReg m_clear;\r\n\tTReg m_set;\r\n}" +
                    ";\r\n\r\n/**\r\n * Helper class for memory registers access.\r\n */\r\ntemplate<typename T" +
                    "Int, typename TReg>\r\nclass Memory\r\n{\r\n    static_assert(std::is_integral_v<TInt>" +
                    ");\r\n    static_assert(sizeof(TReg) == sizeof(TInt));\r\n    static_assert(std::is_" +
                    "convertible_v<TInt, TReg>);\r\n\r\npublic:\r\n    \r\n    auto operator=(TReg value) -> " +
                    "Memory&\r\n    {\r\n        m_value.store(value.value(), std::memory_order_relaxed);" +
                    "\r\n        return *this;\r\n    }\r\n\r\n    operator TReg() const\r\n    {\r\n        retu" +
                    "rn load();\r\n    }\r\n\r\n    [[nodiscard]] auto load() const -> TReg\r\n    {\r\n       " +
                    " return m_value.load(std::memory_order_relaxed);\r\n    }\r\n\r\n    auto operator |=(" +
                    "TReg value) -> Memory&\r\n    {\r\n        m_value.fetch_or(value.value(), std::memo" +
                    "ry_order_relaxed);\r\n        return *this;\r\n    }\r\n\r\n    auto operator &=(TReg va" +
                    "lue) -> Memory&\r\n    {\r\n        m_value.fetch_and(value.value(), std::memory_ord" +
                    "er_relaxed);\r\n        return *this;\r\n    }\r\n\r\n    auto operator ^=(TReg value) -" +
                    "> Memory&\r\n    {\r\n        m_value.fetch_xor(value.value(), std::memory_order_rel" +
                    "axed);\r\n        return *this;\r\n    }\r\n\r\n    auto operator <<=(ClearSet<TReg> val" +
                    "ue) -> Memory&\r\n    {\r\n        auto previous = m_value.load(std::memory_order_re" +
                    "laxed);\r\n        while(!m_value.compare_exchange_strong(previous, (previous & ~v" +
                    "alue.clear().value()) | value.set().value(), std::memory_order_relaxed));\r\n     " +
                    "   return *this;\r\n    }\r\n\r\nprivate:\r\n    volatile std::atomic<TInt> m_value;\r\n};" +
                    "\r\n\r\n/**\r\n * Helper class for read only memory registers access.\r\n */\r\ntemplate<t" +
                    "ypename TInt, typename TReg>\r\nclass ReadOnlyMemory\r\n{\r\n    static_assert(std::is" +
                    "_integral_v<TInt>);\r\n    static_assert(sizeof(TReg) == sizeof(TInt));\r\n    stati" +
                    "c_assert(std::is_convertible_v<TInt, TReg>);\r\n\r\npublic:\r\n    \r\n    operator TReg" +
                    "() const\r\n    {\r\n        return load();\r\n    }\r\n\r\n    [[nodiscard]] auto load() " +
                    "const -> TReg\r\n    {\r\n        return m_value.load(std::memory_order_relaxed);\r\n " +
                    "   }\r\n\r\nprivate:\r\n    volatile std::atomic<TInt> m_value;\r\n};\r\n\r\n/**\r\n * Helper " +
                    "class for write only memory registers access.\r\n */\r\ntemplate<typename TInt, type" +
                    "name TReg>\r\nclass WriteOnlyMemory\r\n{\r\n    static_assert(std::is_integral_v<TInt>" +
                    ");\r\n    static_assert(sizeof(TReg) == sizeof(TInt));\r\n    static_assert(std::is_" +
                    "convertible_v<TInt, TReg>);\r\n\r\npublic:\r\n    \r\n    auto operator=(TReg value) -> " +
                    "WriteOnlyMemory&\r\n    {\r\n        m_value.store(value.value(), std::memory_order_" +
                    "relaxed);\r\n        return *this;\r\n    }\r\n\r\nprivate:\r\n    volatile std::atomic<TI" +
                    "nt> m_value;\r\n};\r\n\r\ntemplate<std::size_t Size>\r\nclass __attribute__((packed)) Pa" +
                    "dding\r\n{\r\n    static_assert(Size != 0);\r\n    std::array<uint8_t, Size> reserved;" +
                    "\r\n};\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public class MemoryBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
